version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Kaavish2025
      MYSQL_DATABASE: fyp_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Kaavish2025
      DB_NAME: fyp_db
    # wrap Gunicorn with our wait script:
    command: ["/wait-for-db.sh", "db", "gunicorn", "--bind", "0.0.0.0:5000", "app:app"]

volumes:
  db_data: